### ISSUE TITLE
What is that for ?

### ISSUE THREAD

**Issue by ArtanisInc** [riverar/Remove-HypervisorChecks#2]
Why removing hyper v check ?

**Comment by GirardiF** [comment]
Sorry for late response.
This is the scenario: you have a Windows 10 virtual machine as guest on Hyper-V and you want to passthrough a GPU to this virtual machine. When you install the GPU's driver in the vm, you will get the infamous "error 43". This happens because AMD and NVidia consumers drivers checks if they are in the presence of a hypervisor and, in this case, block the use of the GPU.

So, this script patch the NVidia driver to bypass the check and to permit the use of the GPU inside a virtual machine.
